-- Generated by Oracle SQL Developer REST Data Services 19.2.1.247.2212
-- Exported REST Definitions from ORDS Schema Version 3.0.9.348.07.16
-- Schema: DBMONITORING   Date: Sun Dec 22 17:15:17 GMT 2019
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DBMONITORING',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'dbmonitoring',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'datafiles',
      p_base_path      => '/datafiles/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'datafiles',
      p_pattern        => 'dfs',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'datafiles',
      p_pattern        => 'dfs',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from DBMonitoring.datafile where active = 1'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'quotas',
      p_base_path      => '/quotas/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'quotas',
      p_pattern        => 'qts',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'quotas',
      p_pattern        => 'qts',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select ts.name, u.username, q.used, q.max_size, q.timestamp from DBMonitoring.quota q join DBMonitoring.tablespace ts on ts.tablespace_id = q.tablespace_id join DBMonitoring.users u on u.user_id = q.user_id where q.active = 1'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'quotashist',
      p_base_path      => '/quotashist/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'quotashist',
      p_pattern        => 'qth',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'quotashist',
      p_pattern        => 'qth',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select ts.name, u.username, q.used, q.max_size, q.timestamp from DBMonitoring.quota_history q join DBMonitoring.tablespace ts on ts.tablespace_id = q.tablespace_id join DBMonitoring.users u on u.user_id = q.user_id'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'resources',
      p_base_path      => '/resources/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'resources',
      p_pattern        => 'src',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'resources',
      p_pattern        => 'src',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from DBMonitoring.resources'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'sessions',
      p_base_path      => '/sessions/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sessions',
      p_pattern        => 'sess',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sessions',
      p_pattern        => 'sess',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from DBMonitoring.sessions where active = 1'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'tablespaces',
      p_base_path      => '/tablespaces/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'tablespaces',
      p_pattern        => 'ts',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'tablespaces',
      p_pattern        => 'ts',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from DBMonitoring.tablespace where active = 1'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'tablespaceshist',
      p_base_path      => '/tablespaceshist/',
      p_items_per_page =>  1000,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'tablespaceshist',
      p_pattern        => 'tsh',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'tablespaceshist',
      p_pattern        => 'tsh',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  1000,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from DBMonitoring.tablespace_history order by tablespace_id, timestamp'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'users',
      p_base_path      => '/users/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'users',
      p_pattern        => 'usr',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'users',
      p_pattern        => 'usr',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  100,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from dbmonitoring.users where active = 1'
      );


  COMMIT; 
END;