CREATE TABLESPACE aebdtp_tables
DATAFILE  'aebdtp_tables.dbf'
SIZE 100M;


CREATE TEMPORARY TABLESPACE aebdtp_temp
TEMPFILE  'aebdtp_temp.dbf'
SIZE 50M 
AUTOEXTEND ON;

SELECT * FROM dba_tablespaces;

CREATE USER DBMONITORING
    IDENTIFIED BY pass
    DEFAULT TABLESPACE aebdtp_tables
    TEMPORARY TABLESPACE aebdtp_temp;
    
    
GRANT CONNECT TO DBMONITORING;

GRANT CREATE SESSION TO DBMONITORING;

GRANT CREATE table TO DBMONITORING;

GRANT CREATE view TO DBMONITORING;

GRANT DROP ANY table TO DBMONITORING;

GRANT CREATE procedure TO DBMONITORING;

GRANT CREATE sequence TO DBMONITORING;

GRANT ALTER ANY table TO  DBMONITORING;

GRANT CREATE ANY TRIGGER TO DBMONITORING;

ALTER USER DBMONITORING QUOTA 300M ON aebdtp_tables;

GRANT UPDATE ANY TABLE TO DBMONITORING;

GRANT CREATE TABLESPACE TO DBMONITORING;

GRANT ALTER TABLESPACE TO DBMONITORING;

GRANT DROP TABLESPACE TO DBMONITORING;

GRANT CREATE USER TO DBMONITORING;

GRANT DROP USER TO DBMONITORING;
