CREATE OR REPLACE TRIGGER UPDATE_QUOTA
AFTER UPDATE 
ON QUOTA
FOR EACH ROW
BEGIN
    INSERT INTO QUOTA_HISTORY VALUES(:OLD.TABLESPACE_ID,:OLD.USER_ID,
                                    :OLD.USED,:OLD.MAX_SIZE,:OLD.TIMESTAMP,
                                    :OLD.ACTIVE);
END;