CREATE OR REPLACE TRIGGER UPDATE_QUOTA
AFTER UPDATE
ON QUOTA
FOR EACH ROW
BEGIN
    IF :OLD.MAX_SIZE != :NEW.MAX_SIZE THEN
        INSERT INTO QUOTA_HISTORY VALUES(:OLD.TABLESPACE_ID,:OLD.USER_ID,
                                    :OLD.USED,:OLD.MAX_SIZE,:OLD.TIMESTAMP,
                                    :OLD.ACTIVE);
    END IF;
END;

CREATE OR REPLACE TRIGGER UPDATE_TABLESPACES
AFTER UPDATE
ON TABLESPACE
FOR EACH ROW
BEGIN
    IF :OLD.TIMESTAMP != :NEW.TIMESTAMP THEN
        INSERT INTO TABLESPACE_HISTORY VALUES(:OLD.TABLESPACE_ID,
                                        :OLD.NAME,
                                        :OLD.STATUS,
                                        :OLD.FREE_PERCENTAGE,
                                        :OLD.TIMESTAMP,
                                        :OLD.ACTIVE);
    END IF;
END;

CREATE OR REPLACE TRIGGER UPDATE_TABLESPACES_STATUS
AFTER UPDATE
ON TABLESPACE
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'OFFLINE' THEN
        UPDATE TABLESPACE_HISTORY TH
        SET STATUS = 'OFFLINE'
        WHERE :NEW.TABLESPACE_ID = TH.TABLESPACE_ID;
    END IF;
END;